### ISSUE TITLE
How can I support this library?

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [charlieAndroidDev/Instagram4Android#33]
**[not a programming issue]**
Hello, I do know that this is open source project but I would like to show my support to the creator, do @charlieAndroidDev have a twitter account, patreon or something?
I don't know if I will donate something but I will try to show my support how I can ❤️

**Comment by charlieAndroidDev** [comment]
Thank you very much for using this library and thank you for wanting to support me!

I have a Bitcoin address here: 1BFLxaSGkk9DRjx7WTg9NkcWtRUzF2Z7qe

I might make some new social media's for public use in the near future so be sure to check out this repos Readme in the future!  Many thanks for any kind of support, money or otherwise that you are able to give!
